// types
import {LayoutListItemGroupNumber} from "@/types/list";

export const PublicRelationsInformationListItem: LayoutListItemGroupNumber[] = [
    {
        id: 1, 
        numtxt: '0101',
        iconType: 'pdf',
        title: 'ประกาศแต่งตั้งประธานศาลปกครองสูงสุด (นายประสิทธิ์ศักดิ์ มีลาภ)',
        book: '146', 
        episode: 'ตอนพิเศษ 269 ง', 
        date: '25 กันยายน 2564', 
        linkUrl: '/public-relations/viewpdf', 
        btnUrl: '#', 
    },
    {
        id: 2, 
        numtxt: '0101',
        iconType: 'pdf',
        title: 'ประกาศแต่งตั้งประธานศาลปกครองสูงสุด (นายประสิทธิ์ศักดิ์ มีลาภ)',
        book: '146', 
        episode: 'ตอนพิเศษ 269 ง', 
        date: '25 กันยายน 2564', 
        linkUrl: '/public-relations/viewpdf', 
        btnUrl: '#', 
    },
    {
        id: 3, 
        numtxt: '0101',
        iconType: 'pdf',
        title: 'ประกาศแต่งตั้งประธานศาลปกครองสูงสุด (นายประสิทธิ์ศักดิ์ มีลาภ)',
        book: '146', 
        episode: 'ตอนพิเศษ 269 ง', 
        date: '25 กันยายน 2564', 
        linkUrl: '/public-relations/viewpdf', 
        btnUrl: '#', 
    },
    {
        id: 4, 
        numtxt: '0101',
        iconType: 'pdf',
        title: 'ประกาศแต่งตั้งประธานศาลปกครองสูงสุด (นายประสิทธิ์ศักดิ์ มีลาภ)',
        book: '146', 
        episode: 'ตอนพิเศษ 269 ง', 
        date: '25 กันยายน 2564', 
        linkUrl: '/public-relations/viewpdf', 
        btnUrl: '#', 
    },
    {
        id: 5, 
        numtxt: '0101',
        iconType: 'pdf',
        title: 'ประกาศแต่งตั้งประธานศาลปกครองสูงสุด (นายประสิทธิ์ศักดิ์ มีลาภ)',
        book: '146', 
        episode: 'ตอนพิเศษ 269 ง', 
        date: '25 กันยายน 2564', 
        linkUrl: '/public-relations/viewpdf', 
        btnUrl: '#', 
    },
    {
        id: 6, 
        numtxt: '0101',
        iconType: 'pdf',
        title: 'ประกาศแต่งตั้งประธานศาลปกครองสูงสุด (นายประสิทธิ์ศักดิ์ มีลาภ)',
        book: '146', 
        episode: 'ตอนพิเศษ 269 ง', 
        date: '25 กันยายน 2564', 
        linkUrl: '/public-relations/viewpdf', 
        btnUrl: '#', 
    },
    {
        id: 7, 
        numtxt: '0101',
        iconType: 'pdf',
        title: 'ประกาศแต่งตั้งประธานศาลปกครองสูงสุด (นายประสิทธิ์ศักดิ์ มีลาภ)',
        book: '146', 
        episode: 'ตอนพิเศษ 269 ง', 
        date: '25 กันยายน 2564', 
        linkUrl: '/public-relations/viewpdf', 
        btnUrl: '#', 
    },
    {
        id: 8, 
        numtxt: '0101',
        iconType: 'pdf',
        title: 'ประกาศแต่งตั้งประธานศาลปกครองสูงสุด (นายประสิทธิ์ศักดิ์ มีลาภ)',
        book: '146', 
        episode: 'ตอนพิเศษ 269 ง', 
        date: '25 กันยายน 2564', 
        linkUrl: '/public-relations/viewpdf', 
        btnUrl: '#', 
    },
]; 