// types
import {LayoutListItemGroup} from "@/types/list";

export const PublicRelationsMediaListItem: LayoutListItemGroup[] = [
    { 
        id: 1, 
        title: 'วีดีโอ', 
        linkUrl: '#',
        orderlist: [
            {
                id: 1, 
                date: '10.02.2025', 
                image: '/img/upload/vdo.jpg', 
                imageType: 'vdo', 
                title: 'คลิปแนะนำวิธีการลงทะเบียนผู้ใช้งาน/คำสั่ง ผ่านแอปพลิเคชัน ศาลปกครอง', 
                linkUrl: '#',
            },
            {
                id: 2, 
                date: '10.02.2025', 
                image: '/img/upload/vdo.jpg', 
                imageType: 'vdo', 
                title: 'คลิปแนะนำวิธีการลงทะเบียนผู้ใช้งาน/คำสั่ง ผ่านแอปพลิเคชัน ศาลปกครอง', 
                linkUrl: '#',
            },
            {
                id: 3, 
                date: '10.02.2025', 
                image: '/img/upload/vdo.jpg', 
                imageType: 'vdo', 
                title: 'คลิปแนะนำวิธีการลงทะเบียนผู้ใช้งาน/คำสั่ง ผ่านแอปพลิเคชัน ศาลปกครอง', 
                linkUrl: '#',
            },
            {
                id: 4, 
                date: '10.02.2025', 
                image: '/img/upload/vdo.jpg', 
                imageType: 'vdo', 
                title: 'คลิปแนะนำวิธีการลงทะเบียนผู้ใช้งาน/คำสั่ง ผ่านแอปพลิเคชัน ศาลปกครอง', 
                linkUrl: '#',
            },
        ],
    },
    { 
        id: 2, 
        title: 'เอกสารประชาสัมพันธ์', 
        linkUrl: '#',
        orderlist: [
            {
                id: 1, 
                date: '10.02.2025', 
                image: '/img/upload/infomation.jpg', 
                imageType: 'book', 
                title: 'เอกสารประชาสัมพันธ์รายปักษ์ ACT News ฉบับที่ 216 (วันที่ 16 - 31 ธันวาคม 2567)', 
                linkUrl: '#',
            },
            {
                id: 2, 
                date: '10.02.2025', 
                image: '/img/upload/infomation.jpg', 
                imageType: 'book', 
                title: 'เอกสารประชาสัมพันธ์รายปักษ์ ACT News ฉบับที่ 216 (วันที่ 16 - 31 ธันวาคม 2567)', 
                linkUrl: '#',
            },
            {
                id: 3, 
                date: '10.02.2025', 
                image: '/img/upload/infomation.jpg', 
                imageType: 'book', 
                title: 'เอกสารประชาสัมพันธ์รายปักษ์ ACT News ฉบับที่ 216 (วันที่ 16 - 31 ธันวาคม 2567)', 
                linkUrl: '#',
            },
            {
                id: 4, 
                date: '10.02.2025', 
                image: '/img/upload/infomation.jpg', 
                imageType: 'book', 
                title: 'เอกสารประชาสัมพันธ์รายปักษ์ ACT News ฉบับที่ 216 (วันที่ 16 - 31 ธันวาคม 2567)', 
                linkUrl: '#',
            },
        ],
    },
    { 
        id: 3, 
        title: 'ภาพกิจกรรม', 
        linkUrl: '#',
        orderlist: [
            {
                id: 1, 
                date: '10.02.2025', 
                image: '/img/upload/news.jpg', 
                imageType: 'ratio-4x3', 
                title: 'ประธานศาลปกครองสูงสุดแถลงนโยบายเน้นย้ำการ บริหารจัดการคดีและบังคับคดีด้วยความเป็นศาลปกครองสูงสุด', 
                linkUrl: '#',
            },
            {
                id: 2, 
                date: '10.02.2025', 
                image: '/img/upload/news.jpg', 
                imageType: 'ratio-4x3', 
                title: 'ประธานศาลปกครองสูงสุดแถลงนโยบายเน้นย้ำการ บริหารจัดการคดีและบังคับคดีด้วยความเป็นศาลปกครองสูงสุด', 
                linkUrl: '#',
            },
            {
                id: 3, 
                date: '10.02.2025', 
                image: '/img/upload/news.jpg', 
                imageType: 'ratio-4x3', 
                title: 'ประธานศาลปกครองสูงสุดแถลงนโยบายเน้นย้ำการ บริหารจัดการคดีและบังคับคดีด้วยความเป็นศาลปกครองสูงสุด', 
                linkUrl: '#',
            },
            {
                id: 4, 
                date: '10.02.2025', 
                image: '/img/upload/news.jpg', 
                imageType: 'ratio-4x3', 
                title: 'ประธานศาลปกครองสูงสุดแถลงนโยบายเน้นย้ำการ บริหารจัดการคดีและบังคับคดีด้วยความเป็นศาลปกครองสูงสุด', 
                linkUrl: '#',
            },
        ],
    },
    { 
        id: 4, 
        title: 'อินโฟกราฟิก', 
        linkUrl: '#',
        orderlist: [
            {
                id: 1, 
                date: '10.02.2025', 
                image: '/img/upload/info-graphic.jpg', 
                imageType: 'book', 
                title: 'เอกสารประชาสัมพันธ์รายปักษ์ ACT News ฉบับที่ 216 (วันที่ 16 - 31 ธันวาคม 2567)', 
                linkUrl: '#',
            },
            {
                id: 2, 
                date: '10.02.2025', 
                image: '/img/upload/info-graphic.jpg', 
                imageType: 'book', 
                title: 'เอกสารประชาสัมพันธ์รายปักษ์ ACT News ฉบับที่ 216 (วันที่ 16 - 31 ธันวาคม 2567)', 
                linkUrl: '#',
            },
            {
                id: 3, 
                date: '10.02.2025', 
                image: '/img/upload/info-graphic.jpg', 
                imageType: 'book', 
                title: 'เอกสารประชาสัมพันธ์รายปักษ์ ACT News ฉบับที่ 216 (วันที่ 16 - 31 ธันวาคม 2567)', 
                linkUrl: '#',
            },
            {
                id: 4, 
                date: '10.02.2025', 
                image: '/img/upload/info-graphic.jpg', 
                imageType: 'book', 
                title: 'เอกสารประชาสัมพันธ์รายปักษ์ ACT News ฉบับที่ 216 (วันที่ 16 - 31 ธันวาคม 2567)', 
                linkUrl: '#',
            },
        ],
    },
]; 