// types
import {LayoutListItemGroupList} from "@/types/list";

export const PublicRelationsAccountListItem: LayoutListItemGroupList[] = [
    { 
        id: 1, 
        title: 'ข้าราชการฝ่ายศาลปกครอง', 
        orderlist: [
            {
                id: 1, 
                position: 'พนักงานคดีปกครองปฏิบัติการ',
                listed: '146', 
                age: '2', 
                expired: '27 พ.ค. 2569', 
                order: '146', 
            },
            {
                id: 2, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
        ],
    },
    { 
        id: 2, 
        title: 'พนักงานราชการศาลปกครอง', 
        orderlist: [
            {
                id: 1, 
                position: 'พนักงานคดีปกครองปฏิบัติการ',
                listed: '146', 
                age: '2', 
                expired: '27 พ.ค. 2569', 
                order: '146', 
            },
            {
                id: 2, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 3, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 4, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 5, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 6, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 7, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
        ],
    },
    { 
        id: 3, 
        title: 'พนักงานราชการศาลปกครอง', 
        orderlist: [
            {
                id: 1, 
                position: 'พนักงานคดีปกครองปฏิบัติการ',
                listed: '146', 
                age: '2', 
                expired: '27 พ.ค. 2569', 
                order: '146', 
            },
            {
                id: 2, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 3, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 4, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 5, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 6, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
            {
                id: 7, 
                position: 'เจ้าพนักงานธุรการปฏิบัติงาน',
                listed: '25', 
                age: '2', 
                expired: '	19 ก.ย. 2569', 
                order: '24', 
            },
        ],
    },
]; 