// types
import {LayoutListItemBook} from "@/types/list";

export const OfficeListItemBookAnnualReport: LayoutListItemBook[] = [
    { 
        id: 1, 
        image: '/img/upload/book3.jpg', 
        title: 'รายงานประจำปี 2566', 
        desc: 'รายงานประจำปี 2566', 
        date: 'เผยแพร่: 15 มกราคม 2567',
        linkUrl: '/office/viewpdf',
        linkDownload: '#',
    },
    { 
        id: 2, 
        image: '/img/upload/book3.jpg', 
        title: 'รายงานประจำปี 2566', 
        desc: 'รายงานประจำปี 2566', 
        date: 'เผยแพร่: 15 มกราคม 2567',
        linkUrl: '/office/viewpdf',
        linkDownload: '#',
    },
    { 
        id: 3, 
        image: '/img/upload/book3.jpg', 
        title: 'รายงานประจำปี 2566', 
        desc: 'รายงานประจำปี 2566', 
        date: 'เผยแพร่: 15 มกราคม 2567',
        linkUrl: '/office/viewpdf',
        linkDownload: '#',
    },
    { 
        id: 4, 
        image: '/img/upload/book3.jpg', 
        title: 'รายงานประจำปี 2566', 
        desc: 'รายงานประจำปี 2566', 
        date: 'เผยแพร่: 15 มกราคม 2567',
        linkUrl: '/office/viewpdf',
        linkDownload: '#',
    },
    { 
        id: 5, 
        image: '/img/upload/book3.jpg', 
        title: 'รายงานประจำปี 2566', 
        desc: 'รายงานประจำปี 2566', 
        date: 'เผยแพร่: 15 มกราคม 2567',
        linkUrl: '/office/viewpdf',
        linkDownload: '#',
    },
    { 
        id: 6, 
        image: '/img/upload/book3.jpg', 
        title: 'รายงานประจำปี 2566', 
        desc: 'รายงานประจำปี 2566', 
        date: 'เผยแพร่: 15 มกราคม 2567',
        linkUrl: '/office/viewpdf',
        linkDownload: '#',
    },
    { 
        id: 7, 
        image: '/img/upload/book3.jpg', 
        title: 'รายงานประจำปี 2566', 
        desc: 'รายงานประจำปี 2566', 
        date: 'เผยแพร่: 15 มกราคม 2567',
        linkUrl: '/office/viewpdf',
        linkDownload: '#',
    },
    { 
        id: 8, 
        image: '/img/upload/book3.jpg', 
        title: 'รายงานประจำปี 2566', 
        desc: 'รายงานประจำปี 2566', 
        date: 'เผยแพร่: 15 มกราคม 2567',
        linkUrl: '/office/viewpdf',
        linkDownload: '#',
    },
]; 