// types
import {LayoutOverviewItem} from "@/types/overview";

export const AdmincourtOverviewItem: LayoutOverviewItem[] = [
    { 
        id: 1, 
        layout: '',
        linkUrl: '/admincourt/list',
        image: '/img/upload/overview/admincourt01.jpg', 
        title: 'ประวัติความเป็นมา', 
        desc: '', 
    },
    { 
        id: 2, 
        layout: '',
        linkUrl: '/admincourt/list',
        image: '/img/upload/overview/admincourt02.jpg', 
        title: 'ตราสัญลักษณ์', 
        desc: '', 
    },
    { 
        id: 3, 
        layout: 'box-4 -special',
        linkUrl: '/admincourt/list',
        image: '/img/upload/overview/admincourt03.jpg', 
        title: 'พระราชดำรัส', 
        desc: 'แนวทางในการปฏิบัติหน้าที่ด้วยความยุติธรรมและสุจริต', 
    },
    { 
        id: 4,
        layout: 'box-2',
        linkUrl: '/admincourt/list',
        image: '/img/upload/overview/admincourt04.jpg', 
        title: 'วิสัยทัศน์และพันธกิจ', 
        desc: '', 
    },
    { 
        id: 5,
        layout: '',
        linkUrl: '/admincourt/list',
        image: '/img/upload/overview/admincourt05.jpg', 
        title: 'เขตอำนาจ ของศาลปกครอง', 
        desc: '', 
    },
    { 
        id: 6,
        layout: '',
        linkUrl: '/admincourt/list',
        image: '/img/upload/overview/admincourt06.jpg', 
        title: 'ผู้บริหารศาลปกครอง',  
        desc: '', 
    },
    { 
        id: 7,
        layout: 'box-2',
        linkUrl: '/admincourt/list',
        image: '/img/upload/overview/admincourt07.jpg', 
        title: 'แผนแม่บทศาลปกครอง', 
        desc: '', 
    },
    // page2
    // { 
    //     id: 8,
    //     layout: 'box-2',
    //     linkUrl: '/admincourt/list',
    //     image: '/img/upload/overview/admincourt08.jpg', 
    //     title: 'นโยบายประธานศาลปกครองสูงสุด', 
    //     desc: '', 
    // },
    // { 
    //     id: 9,
    //     layout: '',
    //     linkUrl: '/admincourt/regions/grid',
    //     image: '/img/upload/overview/admincourt09.jpg', 
    //     title: 'ศาลปกครองในภูมิภาค', 
    //     desc: '', 
    // },
    // { 
    //     id: 10,
    //     layout: '',
    //     linkUrl: '/admincourt/statistics',
    //     image: '/img/upload/overview/admincourt10.jpg', 
    //     title: 'สถิติคดีปกครอง', 
    //     desc: '', 
    // },
    // { 
    //     id: 11,
    //     layout: 'box-2',
    //     linkUrl: '/admincourt/things-to-know/litigation',
    //     image: '/img/upload/overview/admincourt12.jpg', 
    //     title: 'ข้อควรรู้เกี่ยวกับการฟ้องคดีปกครอง', 
    //     desc: '', 
    // },
]; 